[2023-12-22T19:02:56.724+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:02:56.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:02:56.770+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:02:56.769+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:02:56.821+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:02:56.814+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:02:56.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:02:56.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.351 seconds
[2023-12-22T19:03:27.338+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:27.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:03:27.357+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:03:27.357+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:27.372+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:03:27.369+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:03:27.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:27.421+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.099 seconds
[2023-12-22T19:03:57.842+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:57.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:03:57.867+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:03:57.866+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:57.884+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:03:57.881+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:03:57.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:03:57.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.092 seconds
[2023-12-22T19:04:28.093+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:28.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:04:28.104+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:04:28.104+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:28.114+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:04:28.112+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:04:28.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:28.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.066 seconds
[2023-12-22T19:04:58.963+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:58.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:04:58.972+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:04:58.972+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:58.988+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:04:58.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:04:58.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:04:59.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.082 seconds
[2023-12-22T19:05:29.866+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:05:29.869+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:05:29.875+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:05:29.874+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:05:29.890+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:05:29.886+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:05:29.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:05:29.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.097 seconds
[2023-12-22T19:06:00.099+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:00.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:06:00.108+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:06:00.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:00.119+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:06:00.116+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:06:00.121+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:00.167+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.074 seconds
[2023-12-22T19:06:30.626+0000] {processor.py:157} INFO - Started process (PID=420) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:30.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:06:30.633+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:06:30.633+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:30.644+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:06:30.641+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:06:30.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:06:30.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.066 seconds
[2023-12-22T19:07:00.860+0000] {processor.py:157} INFO - Started process (PID=476) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:00.863+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:07:00.868+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:07:00.868+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:00.879+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:07:00.876+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:07:00.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:00.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.063 seconds
[2023-12-22T19:07:31.172+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:31.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:07:31.181+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:07:31.180+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:31.191+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:07:31.189+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:07:31.193+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:07:31.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.067 seconds
[2023-12-22T19:08:01.952+0000] {processor.py:157} INFO - Started process (PID=588) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:01.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:08:01.959+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:08:01.959+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:01.972+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:08:01.969+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:08:01.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:02.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.085 seconds
[2023-12-22T19:08:32.180+0000] {processor.py:157} INFO - Started process (PID=644) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:32.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:08:32.191+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:08:32.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:32.205+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:08:32.201+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:08:32.206+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:08:32.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.081 seconds
[2023-12-22T19:09:02.623+0000] {processor.py:157} INFO - Started process (PID=700) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:02.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:09:02.633+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:09:02.632+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:02.659+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:09:02.654+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:09:02.661+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:02.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.137 seconds
[2023-12-22T19:09:32.991+0000] {processor.py:157} INFO - Started process (PID=756) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:32.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:09:33.011+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:09:33.002+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:33.027+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:09:33.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:09:33.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:09:33.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.098 seconds
[2023-12-22T19:10:03.679+0000] {processor.py:157} INFO - Started process (PID=811) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:03.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:10:03.690+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:10:03.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:03.701+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:10:03.698+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:10:03.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:03.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.074 seconds
[2023-12-22T19:10:34.251+0000] {processor.py:157} INFO - Started process (PID=868) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:34.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:10:34.273+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:10:34.271+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:34.302+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:10:34.297+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:10:34.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:10:34.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.219 seconds
[2023-12-22T19:11:05.421+0000] {processor.py:157} INFO - Started process (PID=924) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:05.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:11:05.429+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:11:05.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:05.439+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:11:05.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:11:05.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:05.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.060 seconds
[2023-12-22T19:11:36.420+0000] {processor.py:157} INFO - Started process (PID=980) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:36.423+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:11:36.429+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:11:36.428+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:36.440+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:11:36.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:11:36.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:11:36.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.060 seconds
[2023-12-22T19:12:07.266+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:07.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:12:07.274+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:12:07.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:07.284+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:12:07.282+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:12:07.287+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:07.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.075 seconds
[2023-12-22T19:12:37.799+0000] {processor.py:157} INFO - Started process (PID=1093) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:37.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:12:37.811+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:12:37.811+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:37.827+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:12:37.823+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:12:37.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:12:37.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.075 seconds
[2023-12-22T19:13:07.991+0000] {processor.py:157} INFO - Started process (PID=1149) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:07.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:13:07.997+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:13:07.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:08.007+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:13:08.004+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:13:08.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:08.043+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.058 seconds
[2023-12-22T19:13:38.546+0000] {processor.py:157} INFO - Started process (PID=1205) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:38.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:13:38.555+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:13:38.554+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:38.565+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:13:38.563+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:13:38.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:13:38.608+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.070 seconds
[2023-12-22T19:14:09.296+0000] {processor.py:157} INFO - Started process (PID=1261) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:09.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:14:09.304+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:14:09.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:09.314+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:14:09.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:14:09.316+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:09.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.062 seconds
[2023-12-22T19:14:39.509+0000] {processor.py:157} INFO - Started process (PID=1318) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:39.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:14:39.517+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:14:39.517+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:39.529+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:14:39.526+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:14:39.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:14:39.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.067 seconds
[2023-12-22T19:15:10.081+0000] {processor.py:157} INFO - Started process (PID=1374) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:10.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:15:10.090+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:15:10.089+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:10.101+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:15:10.098+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:15:10.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:10.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.072 seconds
[2023-12-22T19:15:40.365+0000] {processor.py:157} INFO - Started process (PID=1430) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:40.368+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:15:40.373+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:15:40.372+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:40.383+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:15:40.380+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:15:40.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:15:40.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.062 seconds
[2023-12-22T19:16:10.562+0000] {processor.py:157} INFO - Started process (PID=1486) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:10.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:16:10.571+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:16:10.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:10.582+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:16:10.580+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:16:10.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:10.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.066 seconds
[2023-12-22T19:16:40.816+0000] {processor.py:157} INFO - Started process (PID=1542) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:40.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:16:40.824+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:16:40.823+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:40.834+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:16:40.831+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:16:40.835+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:16:40.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.063 seconds
[2023-12-22T19:17:11.059+0000] {processor.py:157} INFO - Started process (PID=1598) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:11.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:17:11.066+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:17:11.066+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:11.085+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:17:11.081+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:17:11.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:11.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.100 seconds
[2023-12-22T19:17:41.524+0000] {processor.py:157} INFO - Started process (PID=1661) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:41.527+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:17:41.533+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:17:41.532+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:41.545+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:17:41.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:17:41.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:17:41.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.073 seconds
[2023-12-22T19:18:11.907+0000] {processor.py:157} INFO - Started process (PID=1718) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:11.911+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:18:11.916+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:18:11.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:11.930+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:18:11.924+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:18:11.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:11.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.066 seconds
[2023-12-22T19:18:42.216+0000] {processor.py:157} INFO - Started process (PID=1774) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:42.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:18:42.224+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:18:42.223+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:42.237+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:18:42.232+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:18:42.238+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:18:42.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.078 seconds
[2023-12-22T19:19:12.541+0000] {processor.py:157} INFO - Started process (PID=1830) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:12.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:19:12.549+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:19:12.549+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:12.562+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:19:12.558+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:19:12.564+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:12.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.084 seconds
[2023-12-22T19:19:42.756+0000] {processor.py:157} INFO - Started process (PID=1886) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:42.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:19:42.763+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:19:42.763+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:42.773+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:19:42.771+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:19:42.776+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:19:42.823+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.074 seconds
[2023-12-22T19:20:13.375+0000] {processor.py:157} INFO - Started process (PID=1942) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T19:20:13.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T19:20:13.385+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:20:13.385+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T19:20:13.406+0000] {logging_mixin.py:154} INFO - [2023-12-22T19:20:13.399+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 3, in <module>
    from airflow.operators.sensors import GoogleCloudStorageObjectSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-12-22T19:20:13.409+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T19:20:13.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.080 seconds
[2023-12-22T20:13:57.563+0000] {processor.py:157} INFO - Started process (PID=29) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:13:57.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:13:57.599+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:13:57.598+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:14:06.968+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:14:06.960+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 12, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-12-22T20:14:06.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:14:07.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 9.523 seconds
[2023-12-22T20:14:38.081+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:14:38.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:14:38.105+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:14:38.103+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:14:40.028+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:14:40.024+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 12, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-12-22T20:14:40.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:14:40.095+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 2.056 seconds
[2023-12-22T20:15:10.361+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:10.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:15:10.387+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:15:10.386+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:10.946+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:15:10.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 12, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-12-22T20:15:10.947+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:10.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.622 seconds
[2023-12-22T20:15:41.135+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:41.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:15:41.142+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:15:41.141+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:41.770+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:15:41.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag0002.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag0002.py", line 12, in <module>
    'retry_delay': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
[2023-12-22T20:15:41.771+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:15:41.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.667 seconds
[2023-12-22T20:17:44.393+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:17:44.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:17:44.407+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:44.407+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:17:45.748+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:17:46.040+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.039+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-22T20:17:46.069+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.068+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-22T20:17:46.092+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.091+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-22T20:17:46.095+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.094+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:17:46.116+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.114+0000] {dag.py:2963} INFO - Creating ORM DAG for gcs_file_check_dag_2
[2023-12-22T20:17:46.139+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:17:46.139+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:17:46.313+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 1.936 seconds
[2023-12-22T20:18:16.513+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:16.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:18:16.529+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:16.528+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:17.384+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:17.418+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:17.417+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:18:17.454+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:17.454+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:18:17.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.995 seconds
[2023-12-22T20:18:48.382+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:48.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:18:48.397+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:48.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:49.134+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:18:49.182+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:49.181+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:18:49.224+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:18:49.224+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:18:49.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.888 seconds
[2023-12-22T20:19:19.449+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:19.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:19:19.458+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:19.458+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:20.054+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:20.085+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:20.085+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:19:20.168+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:20.167+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:19:20.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.802 seconds
[2023-12-22T20:19:50.483+0000] {processor.py:157} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:50.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:19:50.490+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:50.490+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:51.009+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:19:51.038+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:51.037+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:19:51.067+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:19:51.066+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:19:51.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.623 seconds
[2023-12-22T20:20:21.716+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:21.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:20:21.724+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:21.724+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:22.222+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:22.247+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:22.246+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:20:22.275+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:22.275+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:20:22.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.589 seconds
[2023-12-22T20:20:52.362+0000] {processor.py:157} INFO - Started process (PID=379) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:52.364+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:20:52.369+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:52.368+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:52.933+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:20:52.962+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:52.961+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:20:52.991+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:20:52.990+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:20:53.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.667 seconds
[2023-12-22T20:21:23.105+0000] {processor.py:157} INFO - Started process (PID=431) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:23.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:21:23.117+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:23.116+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:23.905+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:23.976+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:23.973+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:21:24.021+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:24.021+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:21:24.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.969 seconds
[2023-12-22T20:21:54.300+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:54.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:21:54.308+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:54.307+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:54.817+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:21:54.856+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:54.856+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:21:54.889+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:21:54.888+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:21:54.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 0.649 seconds
[2023-12-22T20:22:26.401+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:22:26.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:22:26.434+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:22:26.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:22:27.898+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:22:27.933+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:22:27.932+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:22:27.983+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:22:27.983+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-22T20:22:28.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 1.666 seconds
[2023-12-22T20:22:58.377+0000] {processor.py:157} INFO - Started process (PID=612) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:22:58.385+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:22:58.405+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:22:58.403+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:23:00.153+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:23:03.104+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:23:02.941+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:23:04.855+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:23:04.806+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-15T00:00:00+00:00, run_after=2023-12-16T00:00:00+00:00
[2023-12-22T20:23:10.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 11.874 seconds
[2023-12-22T20:23:59.698+0000] {processor.py:157} INFO - Started process (PID=681) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:23:59.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:23:59.866+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:23:59.865+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:24:29.348+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:24:31.403+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:24:31.279+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:24:32.456+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:24:32.455+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-20T00:00:00+00:00, run_after=2023-12-21T00:00:00+00:00
[2023-12-22T20:24:32.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 33.156 seconds
[2023-12-22T20:25:34.775+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/dag0002.py
[2023-12-22T20:25:34.781+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag0002.py for tasks to queue
[2023-12-22T20:25:34.792+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:25:34.791+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag0002.py
[2023-12-22T20:26:16.197+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:26:16.114+0000] {timeout.py:68} ERROR - Process timed out, PID: 768
[2023-12-22T20:26:16.225+0000] {logging_mixin.py:154} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f60c1659e50>
[2023-12-22T20:26:16.276+0000] {logging_mixin.py:154} WARNING - Traceback (most recent call last):
[2023-12-22T20:26:16.286+0000] {logging_mixin.py:154} WARNING -   File "/usr/local/lib/python3.8/weakref.py", line 345, in remove
[2023-12-22T20:26:16.291+0000] {logging_mixin.py:154} WARNING -     def remove(k, selfref=ref(self)):
[2023-12-22T20:26:16.294+0000] {logging_mixin.py:154} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2023-12-22T20:26:16.336+0000] {logging_mixin.py:154} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2023-12-22T20:26:16.339+0000] {logging_mixin.py:154} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag0002.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.3/best-practices.html#reducing-dag-complexity, PID: 768
[2023-12-22T20:26:22.500+0000] {processor.py:839} INFO - DAG(s) dict_keys(['gcs_file_check_dag_2']) retrieved from /opt/airflow/dags/dag0002.py
[2023-12-22T20:26:23.270+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:26:23.268+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-22T20:26:23.448+0000] {logging_mixin.py:154} INFO - [2023-12-22T20:26:23.446+0000] {dag.py:3722} INFO - Setting next_dagrun for gcs_file_check_dag_2 to 2023-12-22T00:00:00+00:00, run_after=2023-12-23T00:00:00+00:00
[2023-12-22T20:26:23.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag0002.py took 48.868 seconds
