[2023-12-30T13:02:44.928+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-30T13:02:45.441+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-30T13:02:45.475+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-30T13:02:46.284+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_json_file> on 2023-12-14 00:00:00+00:00
[2023-12-30T13:02:46.462+0000] {standard_task_runner.py:57} INFO - Started process 303 to run task
[2023-12-30T13:02:46.687+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_json_file', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmpnqsnrzip']
[2023-12-30T13:02:46.980+0000] {standard_task_runner.py:85} INFO - Job 162: Subtask sense_json_file
[2023-12-30T13:02:51.217+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.sense_json_file scheduled__2023-12-14T00:00:00+00:00 [running]> on host e1038f319166
[2023-12-30T13:02:53.991+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Javad' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='sense_json_file' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-30T13:02:54.166+0000] {logging_mixin.py:154} INFO - Sensing JSON file
[2023-12-30T13:02:54.184+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-30T13:02:54.300+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=sense_json_file, execution_date=20231214T000000, start_date=20231230T130244, end_date=20231230T130254
[2023-12-30T13:02:55.049+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-30T13:02:55.976+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
