[2023-12-19T11:31:39.061+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-12-19T11:31:39.369+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-12-19T11:31:39.373+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-19T11:31:39.941+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_csv_file> on 2023-01-23 00:00:00+00:00
[2023-12-19T11:31:40.539+0000] {standard_task_runner.py:57} INFO - Started process 379 to run task
[2023-12-19T11:31:40.610+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_csv_file', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmp4o2423yv']
[2023-12-19T11:31:40.695+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask sense_csv_file
[2023-12-19T11:31:42.935+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.sense_csv_file scheduled__2023-01-23T00:00:00+00:00 [running]> on host e1038f319166
[2023-12-19T11:31:55.769+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task sense_csv_file ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 379)
[2023-12-19T11:32:08.727+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
