[2023-12-21T09:34:06.793+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-12-21T09:34:07.727+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_json_file scheduled__2023-01-09T00:00:00+00:00 [queued]>
[2023-12-21T09:34:07.746+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-21T09:34:09.707+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_json_file> on 2023-01-09 00:00:00+00:00
[2023-12-21T09:34:11.970+0000] {standard_task_runner.py:57} INFO - Started process 167 to run task
[2023-12-21T09:34:12.126+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_json_file', 'scheduled__2023-01-09T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmptdpr5ds5']
[2023-12-21T09:34:12.608+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask sense_json_file
[2023-12-21T09:34:17.810+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.sense_json_file scheduled__2023-01-09T00:00:00+00:00 [running]> on host e1038f319166
[2023-12-21T09:34:21.816+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Javad' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='sense_json_file' AIRFLOW_CTX_EXECUTION_DATE='2023-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-09T00:00:00+00:00'
[2023-12-21T09:34:21.972+0000] {logging_mixin.py:154} INFO - Sensing JSON file
[2023-12-21T09:34:22.167+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-21T09:34:22.639+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=sense_json_file, execution_date=20230109T000000, start_date=20231221T093406, end_date=20231221T093422
[2023-12-21T09:34:23.814+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-21T09:34:24.872+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
